apiVersion: v1
kind: Pod
metadata:
  name: dependent-envars-demo
spec:
  containers:
    - name: dependent-envars-demo
      args:
        - while true; do echo -en '\n'; printf SERVICE_IP=$SERVICE_IP'\n'; sleep 30; done;
      command:
        - sh
        - -c
      image: busybox:1.28
      env:
        # - name: SERVICE_PORT
        #   value: "80"
         - name: SERVICE_IP
           value: ${SERVICE_IP}
        # - name: PROTOCOL
        #   value: "https"
        - name: UNCHANGED_REFERENCE
          value: "$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"
        - name: SERVICE_ADDRESS
          value: "$PROTOCOL://$SERVICE_IP:$SERVICE_PORT"
        - name: ESCAPED_REFERENCE
          value: "$$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"